apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kubernetes-vossmann-de-tls
spec:
  secretName: kubernetes-vossmann-de
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kubernetes.vossmann.de
  dnsNames:
    - kubernetes.vossmann.de
#    - www.kubernetes.vossmann.de
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kubernetes.vossmann.de
#          - www.kubernetes.vossmann.de
          